robot_info: {
  # measurements in metres
  wheel_baseline: 0.21,
  body_radius: 0.27,
  wheel_radius: 0.0496,
  ticks_per_rev: 360,
  num_sensors: 6,
  ir_error_threshold: 0.21, # after this point the IR becomes unreliable
  sensor_names: [s0, s1, s2, s3, s4, s5],
  # the values of these should correspond to the name of parameters specifying
  # the offsets. Some nodes may try to read in the sensor data using 
  # std::string name(sensor_names[i]+sensor_x_suffix) or something similar
  sensor_x_suffix: _offset_x,
  sensor_y_suffix: _offset_y,
  sensor_z_suffix: _offset_z,
  # assume x axis is parallel to the wheelbase, positive x is to the right,
  # negative to the left. y axis is positive in the forward direction, negative
  # backwards. Measurements are in metres, and are very approximate front left.
  # Rotations are positive to the left, negative to the right, about the z axis.
  s0_offset_x: 0.01,
  s0_offset_y: 0.11,
  s0_offset_z: 0,
  s0_rotation: 90,
  # front right
  s1_offset_x: -0.01,
  s1_offset_y: 0.11,
  s1_offset_z: 0,
  s1_rotation: -90,
  # back left
  s2_offset_x: 0.01,
  s2_offset_y: -0.11,
  s2_offset_z: 0,
  s2_rotation: 90,
  # back right
  s3_offset_x: -0.01,
  s3_offset_y: -0.11,
  s3_offset_z: 0,
  s3_rotation: -90,
  # cross left
  s4_offset_x: 0.066,
  s4_offset_y: 0.0672,
  s4_offset_z: 0,
  s4_rotation: 0,
  # cross right
  s5_offset_x: -0.065,
  s5_offset_y: 0.0648,
  s5_offset_z: 0,
  s5_rotation: 0,
  # camera position
  camera_offset_x: 0,
  camera_offset_y: 0,
  camera_offset_z: 0.27,
  camera_rotation_x: 15,
  camera_fov_h: 57.5,
  camera_fov_v: 45

}
