# subscribed indicates that the node will do modify its state or something
# similar based on the messages received there. For example, publishing to the
# /motor_controller/twist topic will define setpoints for the controller. A node
# may subscribe to other topics as well, but these topics should be "defined" by
# the node.
# Published indicates that this topic somehow originates from the node.
topic_list: {
  robot_topics: {
    subscribed: {pwm_topic: /arduino/pwm},
    published: {
      encoder_topic: /arduino/encoders,
      depth_topic: /camera/depth/image_raw
    }
  },
  controller_topics: {
    basic: {
      subscribed: {twist_topic: /motor_controller/twist}
    },
    motor2: {
      subscribed: {twist_topic: /motor2/twist}
    },
    motor3: {
      subscribed: {twist_topic: /motor3/twist},
      published: {bool_topic: /motor3/is_turning}
    },
    wallfollower: {
      published: {turning_topic: /controller/turn}
    }
  },
  hardware_topics: {
    odometry: {
      published: {odometry_topic: /odometry/odometry}
    },
    ir_sensors: {
      published: {ir_distance_topic: /ir_sensors/dists}
    }

  },
  vision_topics: {
    pixel_detect: {
      published: {blob: /vision/closest_blob}
    }
  },
  mapping_topics: {
    segment_storage: {
      segment_save_dir: /home/ras/data/segments,
      bag_segment_topic: /segment_storage/segments
    },
    segment_stitching: {
      published: {stitched_line_topic: /segment_stitching/stitched_lines }
    },
    map_representation: {
      published: {map_topic: /map }
    }
  }
}
