topic_list: {
  test: /three,
  robot_topics: {
    subscribed: {pwm_topic: /arduino/pwm},
    published: {
      encoder_topic: /arduino/encoders,
      depth_topic: /camera/depth/image_raw
    }
  },
  controller_topics: {
    basic: {
      subscribed: {twist_topic: /motor_controller/twist}
    },
    motor2: {
      subscribed: {twist_topic: /motor2/twist}
    }
  },
  vision_topics: {
    pixel_detect: {
      published: {blob: /vision/closest_blob}
    }
  }
}